theme = "onedark"

[editor]
bufferline = "always"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"

[keys.normal]
";" = "command_mode"
":" = "collapse_selection"
"X" = "extend_line_above"
"a" = ["append_mode", "collapse_selection"]
"i" = ["insert_mode", "collapse_selection"]
"C-r" = ["collapse_selection", "keep_primary_selection"]
"C-x" = ":format"
"C-c" = "collapse_selection"

[keys.insert]
"C-r" = "normal_mode"

[keys.select]
"C-r" = "normal_mode"
