theme = "onedark"

[editor]
bufferline = "always"

[editor.whitespace]
render.newline = "all"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"

[editor.indent-guides]
render = true
character = "â•Ž"
skip-levels = 1

[editor.soft-wrap]
enable = true
max-wrap = 25
max-indent-retain = 0

[keys.normal]
";" = "command_mode"
":" = "collapse_selection"
"a" = ["append_mode", "collapse_selection"]
"i" = ["insert_mode", "collapse_selection"]
"C-r" = ["collapse_selection", "keep_primary_selection"]
"C-space" = ":format"
"C-c" = "collapse_selection"
"X" = "extend_line_above"
"D" = []
"H" = []
"L" = []
"M" = []
"V" = []

# A-hjkl for AST motions
A-h = "select_prev_sibling" # A-p
A-l = "select_next_sibling" # A-n
A-k = "expand_selection"    # A-o
A-j = "shrink_selection"    # A-i
A-p = []
A-n = []
A-o = []
A-i = []
# free: A-qwrtyfgzv
[keys.normal."'"]
"h" = "extend_char_left"
"j" = "extend_visual_line_down"
"k" = "extend_visual_line_up"
"l" = "extend_char_right"
"e" = "extend_next_word_end"
"E" = "extend_next_long_word_end"
"b" = "extend_prev_word_start"
"B" = "extend_prev_long_word_start"
"w" = "extend_next_word_start"
"W" = "extend_next_long_word_start"
[keys.normal.space]
'"' = "@ g%change modified"

[keys.insert]
"C-r" = "normal_mode"
# A-hjkl works like normal hjkl
"A-h" = "move_char_left"
"A-j" = "move_visual_line_down"
"A-k" = "move_visual_line_up"
"A-l" = "move_char_right"

[keys.select]
"C-r" = "normal_mode"
"C-c" = "collapse_selection"
