theme = "onedark"

[editor]
bufferline = "always"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"

[keys.normal]
";" = "command_mode"
":" = "collapse_selection"
"C-c" = ["collapse_selection", "keep_primary_selection"]

[keys.insert]
"C-c" = "normal_mode"
